%define upstream_name    Nmap-Parser
%define upstream_version 1.31

Name:		perl-%{upstream_name}
Version:	%perl_convert_version 1.31
Release:	1

Summary:	Parse nmap scan data with perl
License:	GPL+ or Artistic
Group:		Development/Perl
Url:		http://search.cpan.org/dist/%{upstream_name}
Source0:	http://www.cpan.org/modules/by-module/Nmap/Nmap-Parser-1.31.tar.gz

BuildRequires:	perl-devel
BuildRequires:	perl(Storable)
BuildRequires:	perl(XML::Twig)
BuildArch:	noarch

%description
This module implements a interface to the information contained in an nmap
scan. It is implemented by parsing the xml scan data that is generated by
nmap. This will enable anyone who utilizes nmap to quickly create fast and
robust security scripts that utilize the powerful port scanning abilities
of nmap.

%prep
%setup -q -n %{upstream_name}-%{upstream_version}

%build
perl Makefile.PL INSTALLDIRS=vendor
%make

%check
%make test

%install
%makeinstall_std

%files
%doc Changes LICENSE META.yml
%{_mandir}/man3/*
%{perl_vendorlib}/*

%changelog
* Tue May 31 2011 Guillaume Rousse <guillomovitch@mandriva.org> 1.210.0-1mdv2011.0
+ Revision: 682139
- update to new version 1.21

* Sat Apr 23 2011 Funda Wang <fwang@mandriva.org> 1.200.0-2
+ Revision: 657806
- rebuild for updated spec-helper

* Sat Oct 16 2010 Guillaume Rousse <guillomovitch@mandriva.org> 1.200.0-1mdv2011.0
+ Revision: 586115
- import perl-Nmap-Parser


